apiVersion: v1
kind: Service
metadata:
  name: dispatch
  namespace: three-tier-demo
  labels:
    app: dispatch
spec:
  selector:
    app: dispatch
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  namespace: three-tier-demo
  labels:
    app: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch
          image: "robotshop/rs-dispatch:latest"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        #  livenessProbe:
        #    httpGet:
        #      path: /health
        #      port: http
        #    initialDelaySeconds: 20
        #    periodSeconds: 10
        #  readinessProbe:
        #    httpGet:
        #      path: /health
        #      port: http
        #    initialDelaySeconds: 10
        #    periodSeconds: 5
